language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
branches:
  only:
  - master
  - dev
before_install:
  - yarn global add firebase-tools
install:
  - yarn
before_script:
  - chmod ugo+x ./scripts/test-and-build.sh
  - chmod ugo+x ./scripts/publish.sh
script:
  - ./scripts/test-and-build.sh
  - ./scripts/publish.sh
deploy:
  - provider: firebase
    skip_cleanup: true
    token: $FIREBASE_API_KEY_DEV
    project: dev
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH = dev
  - provider: firebase
    skip_cleanup: true
    token: $FIREBASE_API_KEY
    project: master
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH = master
    